In [221]:
import numpy as np
import pandas as pd
import difflib #this library use to get the closest match 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [222]:
dataset=pd.read_csv("movies.csv")

In [223]:
dataset.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [224]:
dataset.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [225]:
dataset.shape

(4803, 24)

In [226]:
selected_feature=["genres","keywords","tagline","cast","crew","original_language","overview"]

In [227]:
selected_feature

['genres',
 'keywords',
 'tagline',
 'cast',
 'crew',
 'original_language',
 'overview']

In [228]:
# replacing the null value from null string

for feature in selected_feature:
    dataset[feature]=dataset[feature].fillna(" ")

In [229]:
selected_columns=dataset["genres"]+" "+dataset["keywords"]+" " +dataset["tagline"]+" "+dataset["cast"]+" "+dataset["crew"]+" "+dataset["original_language"]

In [230]:
selected_columns

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance   A newlywed couple's honeymoon...
4800    Comedy Drama Romance TV Movie date love at fir...
4801        A New Yorker in Shanghai Daniel Henney Eli...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [231]:
tfidf = TfidfVectorizer()

In [232]:
feature_vector=tfidf.fit_transform(selected_columns)

In [233]:
print(feature_vector)

  (0, 182753)	0.00493654182857004
  (0, 182876)	0.0056658280469332155
  (0, 195386)	0.006976810209587449
  (0, 217262)	0.00650547535067957
  (0, 195789)	0.006509270239937864
  (0, 191623)	0.01343550716872508
  (0, 190277)	0.013948126373944417
  (0, 196741)	0.010342533756281864
  (0, 219125)	0.02133054309750882
  (0, 224617)	0.007881758405006076
  (0, 190652)	0.015676404207997985
  (0, 218869)	0.01343550716872508
  (0, 194773)	0.015089604013735963
  (0, 221254)	0.00444827347538137
  (0, 225603)	0.008052483678631145
  (0, 211356)	0.0077969980195307315
  (0, 212085)	0.017090252824765447
  (0, 216476)	0.01520762358321446
  (0, 225623)	0.014099288287113189
  (0, 226448)	0.010979700766040512
  (0, 216394)	0.01343550716872508
  (0, 218360)	0.012935518049605226
  (0, 224774)	0.01081643346192318
  (0, 219696)	0.018238012690950267
  (0, 204884)	0.011756382373049327
  :	:
  (4802, 191017)	0.12225413350577766
  (4802, 212791)	0.11425551738580922
  (4802, 193687)	0.10543762548796437
  (4802, 211295

In [234]:
#getting the similarity score or similarity confidence value, using cosine simalirty funciton


In [235]:
simialrity=cosine_similarity(feature_vector)

In [236]:
print(simialrity)

[[1.         0.5824403  0.82590706 ... 0.36628177 0.09922776 0.22615882]
 [0.5824403  1.         0.58847233 ... 0.33442661 0.08693684 0.20126428]
 [0.82590706 0.58847233 1.         ... 0.38407363 0.10878847 0.22991406]
 ...
 [0.36628177 0.33442661 0.38407363 ... 1.         0.06015883 0.14642057]
 [0.09922776 0.08693684 0.10878847 ... 0.06015883 1.         0.0396685 ]
 [0.22615882 0.20126428 0.22991406 ... 0.14642057 0.0396685  1.        ]]


In [237]:
simialrity.shape

(4803, 4803)

In [238]:
#getting movie name from user

In [239]:
movie_name=input("enter your fav movie name")
movie_name

'Kung Fu Panda'

In [240]:
#creating a alist with all the movie name 

In [241]:
list_of_all_movies=dataset["title"].tolist()

In [242]:
list_of_all_movies

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',

In [243]:
# finding the close max for the movie name given by the user

In [244]:
find_close_max=difflib.get_close_matches(movie_name, list_of_all_movies)#difflib is use to find the close matches 

for movie in find_close_max:
    print(movie)

Kung Fu Panda
Kung Fu Panda 3
Kung Fu Panda 2


In [245]:
close_match=find_close_max[0]
print(close_match)

Kung Fu Panda


In [246]:
# finding the index of the movie with title

In [247]:
index_of_movie = dataset[dataset.title == close_match]["index"].values[0]
index_of_movie

181

In [248]:
index_of_movie = dataset[dataset.title == close_match].iloc[0]["index"]

index_of_movie

181

In [249]:
#getting the list of same movie 
simialrity_score=list(enumerate(simialrity[index_of_movie]))

In [250]:
simialrity_score

[(0, 0.43456831104872007),
 (1, 0.34457705251492526),
 (2, 0.4408813819486645),
 (3, 0.426783452031146),
 (4, 0.4076224049724499),
 (5, 0.3606093238273603),
 (6, 0.3819563061588825),
 (7, 0.40394239289091916),
 (8, 0.30924515906424904),
 (9, 0.42685501200781556),
 (10, 0.28739328903882166),
 (11, 0.27290335604743166),
 (12, 0.3229428137161849),
 (13, 0.34204843037097515),
 (14, 0.372739962631682),
 (15, 0.3960032635158558),
 (16, 0.4378789086301761),
 (17, 0.3578852514295563),
 (18, 0.29581483897913075),
 (19, 0.4426753380081869),
 (20, 0.43123416942721005),
 (21, 0.2710552629773068),
 (22, 0.4219156198387322),
 (23, 0.33188634130809486),
 (24, 0.3534110283947834),
 (25, 0.3619055418868968),
 (26, 0.4283700055622275),
 (27, 0.4332519521006053),
 (28, 0.44514265582849466),
 (29, 0.3253039402079088),
 (30, 0.4180992448268133),
 (31, 0.3302368886020356),
 (32, 0.3109731898054844),
 (33, 0.36737672816739325),
 (34, 0.24573932672318372),
 (35, 0.3857366515580706),
 (36, 0.4238241422453309),

In [251]:
#sorting the movies based on there similarity score

In [252]:
sorted_similar_movier=sorted(simialrity_score, key=lambda x:x[1], reverse=True)#reverse=true is because we want it into decending order, x:x[1] means that score, if we do x:x[0] this means the index, key=lambda is to finiding the value
sorted_similar_movier

[(181, 1.0000000000000002),
 (137, 0.47383449131672495),
 (231, 0.46379867409062375),
 (343, 0.4628618784660446),
 (212, 0.4496999716855537),
 (569, 0.44950901806748955),
 (828, 0.449350740748734),
 (1541, 0.4465931112588353),
 (412, 0.4461427960778902),
 (718, 0.44577325331076395),
 (28, 0.44514265582849466),
 (82, 0.4449445105156929),
 (130, 0.4436913460803872),
 (4259, 0.4435707417317079),
 (19, 0.4426753380081869),
 (864, 0.4421554785305643),
 (533, 0.4418200040141171),
 (152, 0.44101108741876394),
 (2, 0.4408813819486645),
 (1821, 0.4403026926828384),
 (112, 0.4397805587332632),
 (94, 0.439755981275041),
 (354, 0.43954860230136034),
 (108, 0.4390268803634644),
 (335, 0.43888421005355405),
 (169, 0.43856817384939667),
 (1823, 0.4383550454850147),
 (1594, 0.4380000042464998),
 (16, 0.4378789086301761),
 (66, 0.43729332618918754),
 (363, 0.4372913504738681),
 (157, 0.4372015238581015),
 (95, 0.43685202818588886),
 (1430, 0.4366396067439764),
 (452, 0.4361998749189305),
 (276, 0.43612

In [253]:
#suggesting the name of similar movies based on the index

In [261]:
print("Movies suggested for you: \n")

i = 1

for move in sorted_similar_movier:  # Assuming this contains tuples like (index, similarity_score)
    index = move[0]
    title_from_index = dataset[dataset.index == index]["title"].values[0]

    if i < 21:  # Fixing the indentation
        print(i, ":", title_from_index)
        i += 1


Movies suggested for you: 

1 : Kung Fu Panda
2 : Kung Fu Panda 2
3 : Monsters, Inc.
4 : Toy Story 2
5 : The Day After Tomorrow
6 : The SpongeBob Movie: Sponge Out of Water
7 : Kill Bill: Vol. 1
8 : Toy Story
9 : The Core
10 : Deep Blue Sea
11 : Jurassic World
12 : Dawn of the Planet of the Apes
13 : Bolt
14 : Snow White and the Seven Dwarfs
15 : The Hobbit: The Battle of the Five Armies
16 : Blade II
17 : Monster House
18 : Kung Fu Panda 3
19 : Spectre
20 : Scooby-Doo 2: Monsters Unleashed


In [258]:
#movie recommendation system
movie_name1 = input(' Enter your favourite movie name : ')

list_of_all_titles1 = dataset['title'].tolist()

find_close_match1 = difflib.get_close_matches(movie_name1, list_of_all_titles1)

close_match1 = find_close_match1[0]

index_of_the_movie1 = dataset[dataset.title == close_match1]['index'].values[0]

simialrity_score1=list(enumerate(simialrity[index_of_the_movie1]))

sorted_similar_movies1 = sorted(simialrity_score1, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies1:
  index1 = movie[0]
  title_from_index1 = dataset[dataset.index==index1]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index1)
    i+=1

Movies suggested for you : 

1 . Inception
2 . The Dark Knight
3 . Interstellar
4 . The Dark Knight Rises
5 . The Prestige
6 . Batman Begins
7 . The Chronicles of Riddick
8 . Alexander
9 . Man of Steel
10 . Ant-Man
11 . Batman v Superman: Dawn of Justice
12 . xXx
13 . A.I. Artificial Intelligence
14 . Bad Boys II
15 . The Aviator
16 . Catwoman
17 . Transcendence
18 . The Polar Express
19 . Kill Bill: Vol. 1
20 . Black Hawk Down
21 . Tears of the Sun
22 . The Bourne Supremacy
23 . Spider-Man 2
24 . Angels & Demons
25 . Hulk
26 . The Alamo
27 . Men in Black II
28 . Mission: Impossible II
29 . Collateral Damage
